In [18]:
import pandas as pd 
from mlxtend.preprocessing import OnehotTransactions 
from mlxtend.frequent_patterns import apriori 
from mlxtend.frequent_patterns import association_rules 
from mlxtend.preprocessing import TransactionEncoder

In [19]:
dataset = [['Hot Dogs', 'Buns', 'Ketchup'], 
           ['Hot Dogs', 'Buns'], 
           ['Hot Dogs', 'Coke', 'Chips'], 
           ['Chips', 'Coke'], 
           ['Chips', 'Ketchup'],
           ['Hot Dogs','Coke','Chips']] 
te = TransactionEncoder()
te_ary = te.fit(dataset).transform(dataset)
df = pd.DataFrame(te_ary, columns=te.columns_)
df

    Buns  Chips   Coke  Hot Dogs  Ketchup
0   True  False  False      True     True
1   True  False  False      True    False
2  False   True   True      True    False
3  False   True   True     False    False
4  False   True  False     False     True
5  False   True   True      True    False

In [24]:
frequent_itemsets = apriori(df, min_support=0.3334, use_colnames=True) 
print (frequent_itemsets) 

rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.6)
'''rules = association_rules(frequent_itemsets, metric-"lift", min_threshold=1.2) '''
print (rules) 
support=rules.as_matrix(columns=['support']) 
confidence=rules.as_matrix(columns=['confidence']) 
#print(support) 
#print(confidence) 
'''import random 
import matplotlib.pyplot as plt
for i in range (len(support)): 
                           support[i] = support[i] + 0.0025 * (random.randint(1,10) - 5)
                           confidence[i] = confidence[i] + 0.0025 * (random.randint(1,10) - 5) 
plt.scatter(support, confidence, alpha=0.5, marker="*") 
plt.xlabel('support') 
plt.ylabel('confidence') 
plt.show() '''

    support       itemsets
0  0.666667        (Chips)
1  0.500000         (Coke)
2  0.666667     (Hot Dogs)
3  0.500000  (Chips, Coke)
  antecedents consequents  antecedent support  consequent support  support  \
0     (Chips)      (Coke)            0.666667            0.500000      0.5
1      (Coke)     (Chips)            0.500000            0.666667      0.5

   confidence  lift  leverage  conviction
0        0.75   1.5  0.166667         2.0
1        1.00   1.5  0.166667         inf

C:\Users\Javed\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:7: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  import sys
C:\Users\Javed\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:8: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.

'import random \nimport matplotlib.pyplot as plt\nfor i in range (len(support)): \n                           support[i] = support[i] + 0.0025 * (random.randint(1,10) - 5)\n                           confidence[i] = confidence[i] + 0.0025 * (random.randint(1,10) - 5) \nplt.scatter(support, confidence, alpha=0.5, marker="*") \nplt.xlabel(\'support\') \nplt.ylabel(\'confidence\') \nplt.show() '

In [33]:
dataset2 = [['A', 'B', 'C', 'D','E','F'], 
           ['B', 'C','D','E','F','G'], 
           ['A', 'D', 'E', 'H'], 
           ['A', 'D','F','I','J'], 
           ['B', 'D','E','K']] 
te = TransactionEncoder()
te_ary2 = te.fit(dataset2).transform(dataset2)
df2 = pd.DataFrame(te_ary2, columns=te.columns_)
df2

       A      B      C     D      E      F      G      H      I      J      K
0   True   True   True  True   True   True  False  False  False  False  False
1  False   True   True  True   True   True   True  False  False  False  False
2   True  False  False  True   True  False  False   True  False  False  False
3   True  False  False  True  False   True  False  False   True   True  False
4  False   True  False  True   True  False  False  False  False  False   True

In [34]:
frequent_itemsets = apriori(df2, min_support=0.6, use_colnames=True) 
print (frequent_itemsets) 

rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.8)
'''rules = association_rules(frequent_itemsets, metric-"lift", min_threshold=1.2) '''
print (rules)

    support   itemsets
0       0.6        (A)
1       0.6        (B)
2       1.0        (D)
3       0.8        (E)
4       0.6        (F)
5       0.6     (A, D)
6       0.6     (B, D)
7       0.6     (B, E)
8       0.8     (E, D)
9       0.6     (F, D)
10      0.6  (B, E, D)
  antecedents consequents  antecedent support  consequent support  support  \
0         (A)         (D)                 0.6                 1.0      0.6
1         (B)         (D)                 0.6                 1.0      0.6
2         (B)         (E)                 0.6                 0.8      0.6
3         (E)         (D)                 0.8                 1.0      0.8
4         (D)         (E)                 1.0                 0.8      0.8
5         (F)         (D)                 0.6                 1.0      0.6
6      (B, E)         (D)                 0.6                 1.0      0.6
7      (B, D)         (E)                 0.6                 0.8      0.6
8         (B)      (E, D)                 0.6                 0.8      0.6

   confidence  lift  leverage  conviction
0         1.0  1.00      0.00         inf
1         1.0  1.00      0.00         inf
2         1.0  1.25      0.12         inf
3         1.0  1.00      0.00         inf
4         0.8  1.00      0.00         1.0
5         1.0  1.00      0.00         inf
6         1.0  1.00      0.00         inf
7         1.0  1.25      0.12         inf
8         1.0  1.25      0.12         inf

In [35]:
dataset3 = [['75534', '75535', '75536', '75537','75538','75539'], 
           ['75535', '75539','755374','75536','75535','75535'], 
           ['75537', '75534','75535','75536','75537','75534'], 
           ['75538', '75536','75536','755357','75537','75534'], 
           ['75534', '75536','75537','75537','75535','75539']] 
te = TransactionEncoder()
te_ary3 = te.fit(dataset3).transform(dataset3)
df3 = pd.DataFrame(te_ary3, columns=te.columns_)
df3

   75534  75535  755357  75536  75537  755374  75538  75539
0   True   True   False   True   True   False   True   True
1  False   True   False   True  False    True  False   True
2   True   True   False   True   True   False  False  False
3   True  False    True   True   True   False   True  False
4   True   True   False   True   True   False  False   True

In [36]:
frequent_itemsets = apriori(df3, min_support=0.6, use_colnames=True) 
print (frequent_itemsets) 

rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.8)
'''rules = association_rules(frequent_itemsets, metric-"lift", min_threshold=1.2) '''
print (rules)

    support                      itemsets
0       0.8                       (75534)
1       0.8                       (75535)
2       1.0                       (75536)
3       0.8                       (75537)
4       0.6                       (75539)
5       0.6                (75534, 75535)
6       0.8                (75534, 75536)
7       0.8                (75534, 75537)
8       0.8                (75535, 75536)
9       0.6                (75535, 75537)
10      0.6                (75539, 75535)
11      0.8                (75537, 75536)
12      0.6                (75539, 75536)
13      0.6         (75534, 75535, 75536)
14      0.6         (75534, 75535, 75537)
15      0.8         (75534, 75537, 75536)
16      0.6         (75535, 75537, 75536)
17      0.6         (75539, 75535, 75536)
18      0.6  (75534, 75535, 75537, 75536)
              antecedents     consequents  antecedent support  \
0                 (75534)         (75536)                 0.8
1                 (75536)         (75534)                 1.0
2                 (75534)         (75537)                 0.8
3                 (75537)         (75534)                 0.8
4                 (75535)         (75536)                 0.8
5                 (75536)         (75535)                 1.0
6                 (75539)         (75535)                 0.6
7                 (75537)         (75536)                 0.8
8                 (75536)         (75537)                 1.0
9                 (75539)         (75536)                 0.6
10         (75534, 75535)         (75536)                 0.6
11         (75534, 75535)         (75537)                 0.6
12         (75535, 75537)         (75534)                 0.6
13         (75534, 75537)         (75536)                 0.8
14         (75534, 75536)         (75537)                 0.8
15         (75537, 75536)         (75534)                 0.8
16                (75534)  (75537, 75536)                 0.8
17                (75537)  (75534, 75536)                 0.8
18                (75536)  (75534, 75537)                 1.0
19         (75535, 75537)         (75536)                 0.6
20         (75539, 75535)         (75536)                 0.6
21         (75539, 75536)         (75535)                 0.6
22                (75539)  (75535, 75536)                 0.6
23  (75534, 75535, 75537)         (75536)                 0.6
24  (75534, 75535, 75536)         (75537)                 0.6
25  (75535, 75537, 75536)         (75534)                 0.6
26         (75534, 75535)  (75537, 75536)                 0.6
27         (75535, 75537)  (75534, 75536)                 0.6

    consequent support  support  confidence  lift  leverage  conviction
0                  1.0      0.8         1.0  1.00      0.00         inf
1                  0.8      0.8         0.8  1.00      0.00         1.0
2                  0.8      0.8         1.0  1.25      0.16         inf
3                  0.8      0.8         1.0  1.25      0.16         inf
4                  1.0      0.8         1.0  1.00      0.00         inf
5                  0.8      0.8         0.8  1.00      0.00         1.0
6                  0.8      0.6         1.0  1.25      0.12         inf
7                  1.0      0.8         1.0  1.00      0.00         inf
8                  0.8      0.8         0.8  1.00      0.00         1.0
9                  1.0      0.6         1.0  1.00      0.00         inf
10                 1.0      0.6         1.0  1.00      0.00         inf
11                 0.8      0.6         1.0  1.25      0.12         inf
12                 0.8      0.6         1.0  1.25      0.12         inf
13                 1.0      0.8         1.0  1.00      0.00         inf
14                 0.8      0.8         1.0  1.25      0.16         inf
15                 0.8      0.8         1.0  1.25      0.16         inf
16                 0.8      0.8         1.0  1.25      0.16         inf
17                 0.8      0.8         1.0  1.25      0.16         inf
18                 0.8      0.8         0.8  1.00      0.00         1.0
19                 1.0      0.6         1.0  1.00      0.00         inf
20                 1.0      0.6         1.0  1.00      0.00         inf
21                 0.8      0.6         1.0  1.25      0.12         inf
22                 0.8      0.6         1.0  1.25      0.12         inf
23                 1.0      0.6         1.0  1.00      0.00         inf
24                 0.8      0.6         1.0  1.25      0.12         inf
25                 0.8      0.6         1.0  1.25      0.12         inf
26                 0.8      0.6         1.0  1.25      0.12         inf
27                 0.8      0.6         1.0  1.25      0.12         inf